### ISSUE TITLE
Sometimes blocks scrolling in list view

### ISSUE THREAD

**Issue by artus70** [a-r-m-i-n/scroll#1]
I love this extension, but sometimes it happens in **list view** that the scroll position is automatically held at the bottom of the page. I can then turn the mouse wheel or move the scroll bar - the script then immediately scrolls the view back to the bottom (with fast flickering display).

When the problem occurs, the only way I can break out of this behaviour is by reopening the list view.

Unfortunately, I cannot say exactly how to reproduce the problem. At the moment, I guess that it occasionally occurs when I edit an item and then close it and return to the list view.

TYPO3 11.5.24 / scroll 1.0.2

**Comment by a-r-m-i-n** [comment]
Should be fixed in latest release (for v12).

**Comment by artus70** [comment]
Thanks a lot for your efforts!

But does this mean it isn't compatible with TYPO3 11 anymore?

(I can't upgrade to v12 yet because of too much not yet supported extensions I use.)

**Comment by a-r-m-i-n** [comment]
Yes. The way Javascript works in Backend has been changed significantly in v12, therefore I decided to do not support previous versions.

**Comment by artus70** [comment]
Ok, I understand. So I have to wait until we are ready to do the v12 update - this will probably take a while. 
Thanks anyway!

**Comment by a-r-m-i-n** [comment]
I was able to reconstruct this issue. It happens when you switch from list view (displaying some records from all tables) to single table list view. The issue occuress, when the list of the single table view is longer than it was in the list view of all records. Currently the script is just remembering the pageUid you are currently on, not if you are in a single table.

Going to fix that, and provide a backport for v10/v11 version :)

**Comment by a-r-m-i-n** [comment]
Actually it also was not fixed in v12 release. But now it is 😀
Check out version 1.0.3 or 2.0.1

**Comment by artus70** [comment]
> Actually it also was not fixed in v12 release. But now it is 😀 Check out version 1.0.3 or 2.0.1

That's really great, thanks a lot!
